import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const publicDir = path.join(__dirname, "public");

const MIME_TYPES = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
};

function buildPages({ template, idea }) {
  const baseTitle =
    template === "gaming"
      ? "My Gaming Site"
      : template === "business"
        ? "Zeiter Marketing"
        : template === "portfolio"
          ? "My Portfolio"
          : template === "startup"
            ? "LaunchPad"
            : template === "store"
              ? "Neon Store"
              : idea || "My Website";

  const nav = `
    <nav class="nav">
      <a href="index.html">Home</a>
      <a href="about.html">About</a>
      <a href="contact.html">Contact</a>
    </nav>
  `;

  const styleCss = `
    body { margin: 0; font-family: system-ui, -apple-system, BlinkMacSystemFont, "Inter", sans-serif; background: #020617; color: #e5e7eb; }
    .shell { max-width: 900px; margin: 0 auto; padding: 32px 20px 60px; }
    .nav { display: flex; gap: 16px; margin-bottom: 24px; }
    .nav a { color: #a5f3fc; text-decoration: none; font-size: 14px; }
    .nav a:hover { text-decoration: underline; }
    h1 { font-size: 32px; color: #22d3ee; text-shadow: 0 0 16px rgba(34, 211, 238, 0.7); margin-bottom: 8px; }
    h2 { margin-top: 24px; color: #a5f3fc; }
    .card { margin-top: 18px; padding: 18px 20px; border-radius: 14px; border: 1px solid rgba(34, 211, 238, 0.3); background: rgba(15, 23, 42, 0.9); }
    .btn { display: inline-block; margin-top: 16px; padding: 10px 18px; border-radius: 999px; border: none; background: linear-gradient(135deg, #22d3ee, #6366f1); color: #020617; font-weight: 600; text-decoration: none; font-size: 14px; }
  `;

  const indexHtml = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>${baseTitle}</title><link rel="stylesheet" href="style.css"></head><body><div class="shell">${nav}<h1>${baseTitle}</h1><div class="card"><h2>Welcome</h2><p>This is the home page for ${baseTitle}.</p><p>Generated by your AI Website Generator.</p><a href="contact.html" class="btn">Get in touch</a></div></div></body></html>`;

  const aboutHtml = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>About - ${baseTitle}</title><link rel="stylesheet" href="style.css"></head><body><div class="shell">${nav}<h1>About</h1><div class="card"><p>${baseTitle} is a website generated from a single idea or template.</p><p>Customize this page to tell your story, mission, and background.</p></div></div></body></html>`;

  const contactHtml = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Contact - ${baseTitle}</title><link rel="stylesheet" href="style.css"></head><body><div class="shell">${nav}<h1>Contact</h1><div class="card"><p>Drop your contact details here.</p><p>Email: you@example.com</p></div></div></body></html>`;

  return {
    "index.html": indexHtml,
    "about.html": aboutHtml,
    "contact.html": contactHtml,
    "style.css": styleCss,
  };
}

const server = createServer(async (req, res) => {
  if (req.method === "POST" && req.url === "/generate-site") {
    let body = "";
    req.on("data", (chunk) => {
      body += chunk;
    });

    req.on("end", () => {
      try {
        const payload = body ? JSON.parse(body) : {};
        const pages = buildPages(payload);
        res.writeHead(200, { "Content-Type": "application/json; charset=utf-8" });
        res.end(JSON.stringify({ pages }));
      } catch {
        res.writeHead(400, { "Content-Type": "application/json; charset=utf-8" });
        res.end(JSON.stringify({ error: "Invalid JSON" }));
      }
    });
    return;
  }

  const requestPath = req.url === "/" ? "/index.html" : req.url;
  const safePath = path.normalize(requestPath).replace(/^\/+/, "");
  const filePath = path.join(publicDir, safePath);

  if (!filePath.startsWith(publicDir)) {
    res.writeHead(403).end("Forbidden");
    return;
  }

  try {
    const file = await readFile(filePath);
    const ext = path.extname(filePath);
    res.writeHead(200, { "Content-Type": MIME_TYPES[ext] || "application/octet-stream" });
    res.end(file);
  } catch {
    res.writeHead(404, { "Content-Type": "text/plain; charset=utf-8" });
    res.end("Not found");
  }
});

const PORT = Number(process.env.PORT) || 3000;
server.listen(PORT, () => {
  console.log(`Running on http://localhost:${PORT}`);
});
